name: deploy-dev-swap

on:
  push:
    branches: 
      - swap-wallet

jobs:
  # This workflow contains a single job called "build"
  build:
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
          
      - name: Installing Dependencies
        run: npm install
      
      - name: build development
        run: npm run build-development
      
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy files 
        run: |
          aws s3 rm s3://${{secrets.S3_BUCKET}} --recursive
          aws s3 cp dist s3://${{secrets.S3_BUCKET}}/ --sse AES256 --recursive
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --path "/*"
